CREATE TABLE [dbo].[Transaction]
(
	[TransactionId] BIGINT NOT NULL IDENTITY PRIMARY KEY, 
    [Processed] DATETIME NOT NULL DEFAULT GETDATE(), 
    [User] NVARCHAR(256) NOT NULL DEFAULT SUSER_SNAME(), 
    [Application] NVARCHAR(128) NOT NULL DEFAULT APP_NAME()
)

GO
